protected/models/Vouchers.php
<?php

/**
 * This is the model class for table "{{vouchers}}".
 *
 * The followings are the available columns in table '{{vouchers}}':
 * @property integer $id
 * @property integer $voucher_for
 * @property string $voucher_date
 * @property integer $company
 * @property integer $project
 * @property integer $voucher_for_user_id
 * @property integer $expense_head
 * @property string $vehicle_number
 * @property string $voucher_number
 * @property integer $staff_id
 * @property string $received_by
 * @property integer $created_by
 * @property string $created_date
 * @property integer $updated_by
 * @property string $updated_date
 *
 * The followings are the available model relations:
 * @property VoucherItems[] $voucherItems
 * @property Company $company0
 * @property Users $createdBy
 * @property ExpenseType $expenseHead
 * @property Projects $project0
 * @property Users $staff
 * @property Users $updatedBy
 * @property Users $voucherForUser
 */
class Vouchers extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{vouchers}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('voucher_for, company, project, voucher_for_user_id, expense_head, staff_id, created_by, updated_by', 'numerical', 'integerOnly' => true),
			array('voucher_for, company, project, voucher_for_user_id, expense_head, staff_id,voucher_number,voucher_date', 'required'),
			array('vehicle_number, voucher_number, received_by', 'length', 'max' => 100),
			array('voucher_date, created_date, updated_date,', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, voucher_for, voucher_date, company, project, voucher_for_user_id, expense_head, vehicle_number, voucher_number, staff_id, received_by, created_by, created_date, updated_by, updated_date', 'safe', 'on' => 'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'voucherItems' => array(self::HAS_MANY, 'VoucherItems', 'voucher_id'),
			'company0' => array(self::BELONGS_TO, 'Company', 'company'),
			'createdBy' => array(self::BELONGS_TO, 'Users', 'created_by'),
			'expenseHead' => array(self::BELONGS_TO, 'ExpenseType', 'expense_head'),
			'project0' => array(self::BELONGS_TO, 'Projects', 'project'),
			'staff' => array(self::BELONGS_TO, 'Users', 'staff_id'),
			'updatedBy' => array(self::BELONGS_TO, 'Users', 'updated_by'),
			'voucherForUser' => array(self::BELONGS_TO, 'Users', 'voucher_for_user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'voucher_for' => 'Voucher For',
			'voucher_date' => 'Voucher Date',
			'company' => 'Company',
			'project' => 'Project',
			'voucher_for_user_id' => 'Voucher For User',
			'expense_head' => 'Expense Head',
			'vehicle_number' => 'Vehicle Number',
			'voucher_number' => 'Voucher Number',
			'staff_id' => 'Site Engineer',
			'received_by' => 'Received By',
			'created_by' => 'Created By',
			'created_date' => 'Created Date',
			'updated_by' => 'Updated By',
			'updated_date' => 'Updated Date',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('voucher_for', $this->voucher_for);
		if (!empty($this->voucher_date))
			$criteria->compare('voucher_date', date('Y-m-d', strtotime($this->voucher_date)), true);
		$criteria->compare('company', $this->company);
		$criteria->compare('project', $this->project);
		$criteria->compare('voucher_for_user_id', $this->voucher_for_user_id);
		$criteria->compare('expense_head', $this->expense_head);
		$criteria->compare('vehicle_number', $this->vehicle_number, true);
		$criteria->compare('voucher_number', $this->voucher_number, true);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('received_by', $this->received_by, true);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('created_date', $this->created_date, true);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('updated_date', $this->updated_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Vouchers the static model class
	 */
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public function getMaxId($filter = null)
	{
		$criteria               = new CDbCriteria;
		$criteria->order = 'id DESC';
		$model  = $this->find($criteria);
		return !empty($model) ? ($model->id) + 1 : '1';
	}

	public function scVendorData($type, $voucher_user_id)
	{
		if ($type == 1) {
			$model = Subcontractor::model()->findByPk($voucher_user_id);
			if (!empty($model))
				return $model->subcontractor_name;
		} elseif ($type == 2) {
			$model = Vendors::model()->findByPk($voucher_user_id);
			if (!empty($model))
				return $model->name;
		} else {
			return '';
		}
	}
}

protected/controllers/VouchersController.php
<?php

class VouchersController extends Controller
{

	public $layout = '//layouts/column2';


	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function accessRules()
	{
		$controller = Yii::app()->controller->id;
		$hidden_actions =  array('dynamicproject', 'index', 'dynamicexpense', 'additems', 'deletevoucher', 'create', 'update', 'deleteitem', 'view');
		$rules = AccessRulesHelper::getRules($controller, $hidden_actions);
		//Additional action rules
		return $rules;
	}

	public function actionCreate()
	{
		$model = new Vouchers;
		$items_model = $voucher_items = new VoucherItems();
		$this->performAjaxValidation($model);
		$user = Users::model()->findByPk(Yii::app()->user->id);
		if (isset($_POST['Vouchers'])) {
			$model->attributes = $_POST['Vouchers'];
			$model->voucher_date = date('Y-m-d', strtotime($model->voucher_date));
			$model->created_by = Yii::app()->user->id;
			$model->created_date = date('Y-m-d H:i:s');
			if (!$model->save()) {
				$errors = json_encode($model->getErrors());
				Yii::app()->user->setFlash('error', $errors);
			} else {
				Yii::app()->user->setFlash('success', "Successfully Created");
				$this->redirect(array('vouchers/update', 'id' => $model->id));
			}
		}
		$this->render('_form', array(
			'model' => $model, 'user_companies' => $user->company_id, 'items_model' => $items_model, 'voucher_items' => $voucher_items
		));
	}

	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);
		$item_id = filter_input(INPUT_GET, 'item', FILTER_SANITIZE_SPECIAL_CHARS);
		$voucher_items = VoucherItems::model()->findAllByAttributes(array('voucher_id' => $id));
		$items_model = new VoucherItems();
		if (!empty($item_id)) {
			$items_model = VoucherItems::model()->findByPk($item_id);
		}
		$this->performAjaxValidation($model);
		$user = Users::model()->findByPk(Yii::app()->user->id);
		if (isset($_POST['Vouchers'])) {
			$model->attributes = $_POST['Vouchers'];
			$model->voucher_date = date('Y-m-d', strtotime($model->voucher_date));
			$model->updated_by = Yii::app()->user->id;
			if (!$model->save()) {
				$errors = json_encode($model->getErrors());
				Yii::app()->user->setFlash('error', $errors);
			} else {
				Yii::app()->user->setFlash('success', "Successfully Updated");
			}
		}

		$this->render('_form', array(
			'model' => $model, 'user_companies' => $user->company_id, 'items_model' => $items_model, 'voucher_items' => $voucher_items
		));
	}



	public function actionIndex()
	{
		$model = new Vouchers('search');
		$model->unsetAttributes();  // clear any default values
		$user = Users::model()->findByPk(Yii::app()->user->id);
		if (isset($_GET['Vouchers']))
			$model->attributes = $_GET['Vouchers'];
		$voucher_items = Vouchers::model()->findAll();
		$this->render('index', array(
			'dataProvider' => $voucher_items, 'model' => $model, 'user_companies' => $user->company_id
		));
	}


	public function actiondynamicProject()
	{
		$voucher_type = filter_input(INPUT_POST, 'voucher_type', FILTER_SANITIZE_SPECIAL_CHARS);
		$company_id = filter_input(INPUT_POST, 'company_id', FILTER_SANITIZE_SPECIAL_CHARS);
		$projects_list = "<option value=''>Select Project</option>";
		$voucher_user_lists = "<option value=''>Select </option>";
		$voucher_users = array();
		if (!empty($company_id)) {
			if ($voucher_type == 1) {
				$voucher_user_lists = "<option value=''>Select Subcontractor</option>";
				$voucher_users = Subcontractor::model()->findAll(
					'FIND_IN_SET(:company_id,company_id)',
					array(':company_id' => (int) $_POST['company_id'])
				);
				$voucher_users = CHtml::listData($voucher_users, 'subcontractor_id', 'subcontractor_name');
			} elseif ($voucher_type == 2) {
				$voucher_user_lists = "<option value=''>Select Vendor</option>";
				$voucher_users = Vendors::model()->findAll(
					'FIND_IN_SET(:company_id,company_id)',
					array(':company_id' => (int) $_POST['company_id'])
				);
				$voucher_users = CHtml::listData($voucher_users, 'vendor_id', 'name');
			}
			$projects = Projects::model()->findAll(
				'FIND_IN_SET(:company_id,company_id)',
				array(':company_id' => (int) $_POST['company_id'])
			);
			$projects = CHtml::listData($projects, 'pid', 'name');
			foreach ($projects as $value => $name)
				$projects_list .= CHtml::tag('option', array('value' => $value), CHtml::encode($name), true);
			foreach ($voucher_users as $value => $name)
				$voucher_user_lists .= CHtml::tag('option', array('value' => $value), CHtml::encode($name), true);
		}

		$result = array('projects_list' => $projects_list, 'voucher_for_list' => $voucher_user_lists);
		echo json_encode($result);
	}

	public function actiondynamicExpense()
	{
		$data = ExpenseType::model()->findAll(
			'company_id=:company_id',
			array(':company_id' => (int) $_POST['company_id'])
		);
		$data = CHtml::listData($data, 'type_id', 'type_name');
		echo "<option value=''>Select Expense</option>";
		foreach ($data as $value => $name)
			echo CHtml::tag('option', array('value' => $value), CHtml::encode($name), true);
	}
	public function loadModel($id)
	{
		$model = Vouchers::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'vouchers-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	public function actionaddItems()
	{
		if (isset($_POST['VoucherItems'])) {
			if (!empty($_POST['VoucherItems']['id'])) {
				$items_model = VoucherItems::model()->findByPk($_POST['VoucherItems']['id']);
			} else {
				$items_model = new VoucherItems();
			}

			$items_model->attributes = $_POST['VoucherItems'];
			$items_model->created_by = Yii::app()->user->id;
			$items_model->created_date = date('Y-m-d H:i:s');
			if (!$items_model->save()) {
				$errors = json_encode($items_model->getErrors());
				Yii::app()->user->setFlash('error', $errors);
			} else {
				Yii::app()->user->setFlash('success', "Successfully Created");
			}
			$this->redirect(array('vouchers/update', 'id' => $items_model->voucher_id));
		}
	}

	public function actiondeleteVoucher()
	{
		$id = filter_input(INPUT_POST, 'id', FILTER_SANITIZE_SPECIAL_CHARS);
		if (!empty($id)) {
			$model = $this->loadModel($id);
			$voucher_items = VoucherItems::model()->findAllByAttributes(array('voucher_id' => $id));
			$transaction = Yii::app()->db->beginTransaction();
			$result =  $message = '';
			try {
				$result = 1;
				if (!empty($voucher_items)) {
					$items_delete = VoucherItems::model()->deleteAll('voucher_id = :voucher_id', array(':voucher_id' => $id));
					if (!$items_delete) {
						$errors = json_encode($items_delete->getErrors());
						$result = 0;
						throw new Exception($errors);
					}
				}
				if (!$model->delete()) {
					$errors = json_encode($model->getErrors());
					$result = 0;
					throw new Exception($errors);
				}
				$transaction->commit();
			} catch (Exception $error) {
				$message = $error->getMessage();
				$result = 0;
				$transaction->rollBack();
			} finally {
				if (!empty($result) && ($result == 1)) {
					Yii::app()->user->setFlash('success', "Successfully deleted");
				} elseif ($result == 0) {
					Yii::app()->user->setFlash('error', $message);
				} else {
					Yii::app()->user->setFlash('error', 'An error ocured');
				}
			}
		}
	}

	public function actiondeleteItem()
	{
		$id = filter_input(INPUT_POST, 'id', FILTER_SANITIZE_SPECIAL_CHARS);
		$result = array('status' => 0, 'message' => '');
		if (!empty($id)) {
			$model = VoucherItems::model()->findByPk($id);
			if ($model->delete()) {
				Yii::app()->user->setFlash('success', "Successfully deleted");
				$result = array('status' => 1, 'message' => 'Successfully deleted');
			} else {
				$message = json_encode($model->getErrors());
				Yii::app()->user->setFlash('error', $message);
				$result = array('status' => 0, 'message' => $message);
			}
		}
		echo json_encode($result);
	}

	public function actionView($id)
	{
		$voucher_items = VoucherItems::model()->findAllByAttributes(array('voucher_id' => $id));
		$this->render('view', array(
			'model' => $this->loadModel($id), 'voucher_items' => $voucher_items
		));
	}
}

protected/views/vouchers/_item_view.php
<?php
$tblpx = Yii::app()->db->tablePrefix;
if ($index == 0) {
?>
    <thead>
        <tr>
            <?php
            if ($data->voucher->voucher_for == 1) {
            ?>
                <th>Work Label</th>
                <th>No Of Workers</th>

            <?php
            }
            ?>
            <th>Description</th>
            <th>Work Timing/Size</th>
            <th>Net Qty</th>
            <th>Unit</th>

            <?php
            if ((isset(Yii::app()->user->role) && ((in_array('/vendors/paymentedit', Yii::app()->user->menuauthlist)) || (in_array('/vendors/paymentdelete', Yii::app()->user->menuauthlist))))) {
            ?>
                <th></th>
            <?php } ?>

        </tr>
    </thead>
<?php } ?>
<tr id="<?php echo $index; ?>" class="" title="">
    <?php
    if ($data->voucher->voucher_for == 1) {
    ?>
        <td class="pro_back wrap"><?php echo $data->worker_label; ?></td>
        <td class="pro_back wrap"><?php echo $data->no_workers; ?></td>
    <?php } ?>
    <td class="pro_back wrap"><?php echo $data->description; ?></td>
    <td class="pro_back wrap"><?php echo $data->working_time_size; ?></td>
    <td class="pro_back wrap"><?php echo $data->net_quantity . ' '; ?></td>
    <td class="pro_back wrap"><?php echo $data->unit0->unit_name . ' '; ?></td>
    <td class="pro_back">
        <span class="icon icon-options-vertical popover-test" data-toggle="popover" data-placement="left" type="button" data-html="true" style="cursor: pointer;"></span>
        <div class="popover-content hide">
            <ul class="tooltip-hiden">
                <?php
                if ((in_array('/vendors/paymentedit', Yii::app()->user->menuauthlist))) {
                ?>
                    <li><button id="<?php echo $data->id; ?>" class="btn btn-xs btn-default edit_item">Edit</button></li>
                <?php }
                if ((in_array('/vendors/paymentdelete', Yii::app()->user->menuauthlist))) {
                ?>
                    <li><button id="<?php echo $data->id; ?>" class="btn btn-xs btn-default delete_item">Delete</button></li>
                <?php } ?>
            </ul>
        </div>
    </td>
</tr>
<script>
    $(document).ready(function() {
        $(".popover-test").popover({
            html: true,
            content: function() {
                return $(this).next('.popover-content').html();
            }
        });
        $('[data-toggle=popover]').on('click', function(e) {
            $('[data-toggle=popover]').not(this).popover('hide');
        });
        $('body').on('hidden.bs.popover', function(e) {
            $(e.target).data("bs.popover").inState.click = false;
        });
        $('body').on('click', function(e) {
            $('[data-toggle=popover]').each(function() {
                if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                    $(this).popover('hide');
                }
            });
        });

        $(document).on('click', '.edit_item', function() {
            var voucher_id = $('#Vouchers_id').val();
            var item_id = $(this).attr('id');
            var url = "<?php echo Yii::app()->createAbsoluteUrl("vouchers/update") ?>";
            location.href = url + '&id=' + voucher_id + '&item=' + item_id;
        })

    });
</script>

protected/views/vouchers/_search.php
<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/select2.min.css">
<script type="text/javascript" src="<?php echo Yii::app()->theme->baseUrl; ?>/js/select2.js"></script>
<div class="page_filter clearfix">
    <?php $form = $this->beginWidget('CActiveForm', array(
        'action' => Yii::app()->createUrl($this->route),
        'method' => 'get',
    )); ?>
    <div class="filter_elem">
        <?php
        echo $form->dropDownList($model, 'voucher_for', array('1' => 'Subcontractor', '2' => 'Vendor'), array('class' => 'select_box', 'empty' => '-Select Voucher for-'));
        ?>
    </div>

    <div class="filter_elem">
        <?php echo $form->textField($model, 'voucher_date', array('class' => 'form-control', 'autocomplete' => 'off', 'placeholder' => 'Voucher Date')); ?>
    </div>

    <div class="filter_elem">
        <?php
        echo $form->dropDownList($model, 'company', CHtml::listData(Company::model()->findAll(array('condition' => 'id IN (' . $user_companies . ')')), 'id', 'name'), array('ajax' => array(
            'type' => 'POST',
            'url' => Yii::app()->createUrl('vouchers/dynamicproject'),
            'dataType' => 'JSON',
            'success' => 'js:function(data)'
                . '{'
                . '    $("#Vouchers_project").html(data.projects_list);'
                . '    $("#Vouchers_voucher_for_user_id").html(data.voucher_for_list);'
                . '}',
            'data' => array('company_id' => 'js:this.value', 'voucher_type' => 'js:$(\'input[name="Vouchers[voucher_for]"]:checked\').val()'),
        ), 'class' => 'select_box', 'empty' => '-Select Company-'));
        ?>
    </div>
    <div class="filter_elem">
        <?php
        echo $form->dropDownList($model, 'project', CHtml::listData(Projects::model()->findAll(array('condition' => 'company_id IN (' . $user_companies . ')')), 'pid', 'name'), array('ajax' => array(
            'type' => 'POST',
            'url' => Yii::app()->createAbsoluteURL('expenses/dynamicDropdown'),
            'dataType' => 'JSON',
            'success' => 'js:function(data)'
                . '{'
                . '    $("#Vouchers_expense_head").html(data.expenses);'
                . '}',
            'data' => array('project' => 'js:this.value', 'bill' => 0, 'expId' => 0)
        ), 'class' => 'select_box', 'empty' => '-Select Project-'));
        ?>
    </div>
    <div class="filter_elem">
        <?php echo $form->textField($model, 'voucher_number', array('class' => 'form-control', 'placeholder' => 'Voucher Number')); ?>
    </div>
    <div class="filter_elem filter_btns">
        <?php echo CHtml::submitButton('Go', array('class' => 'btn-search')); ?>
        <?php echo CHtml::resetButton('Clear', array('onclick' => 'javascript:location.href="' . $this->createUrl('vouchers/index') . '"')); ?>
    </div>
    <?php $this->endWidget(); ?>
</div>
<script>
    $(document).ready(function() {
        $(".select_box").select2();
        $("#Vouchers_voucher_date").datepicker({
            dateFormat: 'dd-mm-yy'
        });
    });
</script>

protected/views/vouchers/index.php
<div class="container" id="expense">
    <div class="loading-overlay">
        <span class="fa fa-spinner fa-3x fa-spin"></span>
    </div>
    <div class="expenses-heading">
        <div class="clearfix">
            <?php if ((isset(Yii::app()->user->role) && (in_array('/vendors/paymentcreate', Yii::app()->user->menuauthlist)))) { ?>
                <a href="index.php?r=vouchers/create" class="btn btn-primary  pull-right mt">Add Entry</a>
            <?php } ?>
            <h2>Vouchers</h2>
        </div>
    </div>

    <div class="daybook form">
        <?php if (Yii::app()->user->hasFlash('success')) : ?>
            <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <?php echo Yii::app()->user->getFlash('success'); ?>
            </div>
        <?php endif; ?>


        <?php if (Yii::app()->user->hasFlash('error')) : ?>
            <div class="alert alert-danger  alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <?php echo Yii::app()->user->getFlash('error'); ?>
            </div>
        <?php endif; ?>
    </div>
    <div>
        <div id="errormessage"></div>
    </div>
    <div class="daybook">
        <div class="">
            <?php $this->renderPartial('_search', array(
                'model' => $model, 'user_companies' => $user_companies
            )); ?>
            <div id="daybook-entry">
                <?php $this->widget('zii.widgets.CListView', array(
                    'id' => 'vouchers-grid',
                    'dataProvider' => $model->search(),
                    'itemView' => '_list',
                    'id' => 'id',
                    'enableSorting' => 1,
                    'enablePagination' => true,
                    'template' => '<div>{summary}{sorter}</div><div id="parent"><table width="100" id="fixTable" class="table total-table">{items}</table></div>{pager}',
                    'enablePagination' => false
                )); ?>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).on('click', '.delete_voucher', function(e) {
        e.preventDefault();
        var answer = confirm("Are you sure you want to delete?");
        if (answer) {
            $('.loading-overlay').addClass('is-active');
            var rowId = $(this).attr("id");
            var date = $("#Vouchers_voucher_date").val();
            $.ajax({
                type: "POST",
                data: {
                    id: rowId,
                    date: date
                },
                url: "<?php echo Yii::app()->createUrl("vouchers/deletevoucher") ?>",
                success: function(data) {
                    location.reload();
                }
            })
        }

    })
    $(document).on('click', '.edit_voucher', function() {
        var id = $(this).attr('id');
        var url = "<?php echo Yii::app()->createAbsoluteUrl("vouchers/update") ?>";
        location.href = url + '&id=' + id;
    })
    $(document).on('click', '.view_voucher', function() {
        var id = $(this).attr('id');
        var url = "<?php echo Yii::app()->createAbsoluteUrl("vouchers/view") ?>";
        location.href = url + '&id=' + id;
    })
    $(document).ajaxComplete(function() {
        $('.loading-overlay').removeClass('is-active');
        $('#loading').hide();
    });
</script>

protected/views/vouchers/view.php
<?php
/* @var $this VouchersController */
/* @var $model Vouchers */

$this->breadcrumbs = array(
    'Vouchers' => array('index'),
    $model->id,
);

?>
<div class="container">
    <div class="clearfix">
        <div class="pull-left">
            <h3 class="viewhead">Voucher #<?php echo $model->voucher_number; ?></h3>
        </div>
        <?php echo CHtml::link('Vouchers', array('vouchers/index'), array('class' => 'btn btn-primary pull-right mt')); ?>

    </div>

    <div class="block_purchase">
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label>COMPANY :</label>
                    <div><?php echo $model->company0->name; ?></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>PROJECT :</label>
                    <div><?php echo $model->project0->name; ?></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>SUBCONTRACTOR :</label>
                    <div><?php echo $model->scVendorData($model->voucher_for, $model->voucher_for_user_id); ?></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>VOUCHER DATE :</label>
                    <div><?php echo $model->voucher_date; ?></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label>EXPENSE HEAD :</label>
                    <div><?php echo $model->expenseHead->type_name; ?></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>VEHICLE NUMBER :</label>
                    <div><?php echo $model->vehicle_number ?></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>VOUCHER NUMBER :</label>
                    <div><?php echo $model->voucher_number; ?></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label>SITE ENGINEER :</label>
                    <div><?php echo $model->staff->first_name; ?></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label>RECEIVED BY :</label>
                    <div><?php echo $model->received_by; ?></div>
                </div>
            </div>
        </div>
    </div>  
    <div id="table-wrap" class="table-wrap">
        <div class="table-responsive">
            <table border="1" class="table">
                <thead>
                    <tr class="table-header">
                        <th class="text-center">Sl.No</th>
                        <?php
                        if ($model->voucher_for == 1) {
                        ?>
                            <th class="text-center">Work Label</th>
                            <th class="text-center">No Of Workers</th>
                        <?php } ?>
                        <th class="text-center">Description</th>
                        <th class="text-center">Work Timing/Size</th>
                        <th class="text-center">Net Qty</th>
                    </tr>
                </thead>
                <tbody class="addrow">
                    <?php
                    $i = 1;
                    foreach ($voucher_items as $items) {
                    ?>
                        <tr>
                            <td><?php echo $i; ?></td>

                            <?php
                            if ($model->voucher_for == 1) {
                            ?>
                                <td><?php echo $items->worker_label; ?></td>
                                <td><?php echo $items->no_workers; ?></td>
                            <?php } ?>
                            <td><?php echo $items->description; ?></td>
                            <td><?php echo $items->working_time_size; ?></td>
                            <td><?php echo $items->net_quantity . ' '; ?></td>
                        </tr>
                    <?php
                        $i++;
                    }
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>