protected/controllers/ClientsController.php
<?php

class ClientsController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
          
        /* return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('view', 'viewpartial', 'newlist'),
                'users' => array('@'),
                'expression' => 'yii::app()->user->role<=3',
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
                'expression' => 'yii::app()->user->role<=2',
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('delete'),
                'users' => array('@'),
                'expression' => 'yii::app()->user->role==1',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        ); */
           $accessArr = array();
           $accessauthArr = array();
           $controller = Yii::app()->controller->id;
           if(isset(Yii::app()->user->menuall)){
               if (array_key_exists($controller, Yii::app()->user->menuall)) {
                   $accessArr = Yii::app()->user->menuall[$controller];
               } 
           }

           if(isset(Yii::app()->user->menuauth)){
               if (array_key_exists($controller, Yii::app()->user->menuauth)) {
                   $accessauthArr = Yii::app()->user->menuauth[$controller];
               }
           }
           $access_privlg = count($accessauthArr);
           return array(
               array('allow', // allow all users to perform 'index' and 'view' actions
                   'actions' => $accessArr,
                   'users' => array('@'),
                   'expression' => "$access_privlg > 0",
               ),

               array('allow', // allow admin user to perform 'admin' and 'delete' actions
                   'actions' => $accessauthArr,
                   'users' => array('@'),
                   'expression' => "$access_privlg > 0",
               ),
               array('deny',  // deny all users
                   'users'=>array('*'),
               ),
           );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionViewpartial($id) {
        $this->renderPartial('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    public function actionView1($id) {
        if (Yii::app()->request->isAjaxRequest) {
            //outputProcessing = true because including css-files ...
            $this->renderPartial('view', array(
                'model' => $this->loadModel($id),
                    ), false, true);
            //js-code to open the dialog    
            if (!empty($_GET['asDialog']))
                echo CHtml::script('$("#dlg-clients-view").dialog("open")');
            Yii::app()->end();
        } else
            $listproject = Projects::model()->findAllByAttributes(array(
                'client_id' => $id,
            ));

        $this->render('view', array(
            'model' => $this->loadModel($id), 'getdata' => $listproject,
        ));
    }

    public function actionView($id) {
//        	if ( isset( $_GET[ 'pageSizes' ] ) )
//{
//Yii::app()->user->setState( 'pageSizes', (int) $_GET[ 'pageSizes' ] );
//unset( $_GET[ 'pageSizes' ] );
//} 


        if (Yii::app()->request->isAjaxRequest) {
            //outputProcessing = true because including css-files ...
            $this->renderPartial('view', array(
                'model' => $this->loadModel($id),
                    ), false, true);
            //js-code to open the dialog    
            if (!empty($_GET['asDialog']))
                echo CHtml::script('$("#dlg-clients-view").dialog("open")');
            Yii::app()->end();
        } else
            $Criteria = new CDbCriteria();
        $Criteria->select = "*";

        $Criteria->compare('clntid', $id);
        $Criteria->group = 'pjctid';
        $count_deal = PaymentReport::model()->count($Criteria);


        $pages = new CPagination($count_deal);
        $pages->pageSize = 5;
        $pages->applyLimit($Criteria);
        $listproject = PaymentReport::model()->findAll($Criteria);
        $this->render('view', array(
            'model' => $this->loadModel($id), 'getdata' => $listproject, 'pages' => $pages, 'clid' => $id
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
		
		 if(isset($_GET['layout']))
                $this->layout = false;
        $model = new Clients;
        $tblpx = Yii::app()->db->tablePrefix;
        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);
		

        if (isset($_POST['Clients'])) { 
			
			//print_r($_POST['Clients']); die;         
            $model->attributes = $_POST['Clients'];
            
            if($_POST['Clients']['project_type'] != 2 )
            {
			$model->local_address = '';
            $model->contact_person = '';
			}else{
            $model->local_address = $_POST['Clients']['local_address'];
            $model->contact_person = $_POST['Clients']['contact_person'];
			}
            $model->created_by = yii::app()->user->id;
            $model->created_date = date('Y-m-d');

            $model->updated_by = yii::app()->user->id;
            $model->updated_date = date('Y-m-d');
            if (!empty($_POST['Clients']['company_id'])) {
                $company = implode(",",$_POST['Clients']['company_id']);
                $model->company_id = $company;
            } else {
                $model->company_id = NULL;
            } 
            if ($model->save()) {
                if ($_POST['execute_api'] == 1) {
                $pms_api_integration=ApiSettings::model()->pmsIntegrationStatus();

                if($pms_api_integration ==1){
                    $request = [
                        'origin' => 'coms',
                        'client_id' =>$model->cid,
                        'name' => $model->name,
                        'project_type' => $model->project_type,
                        'status' => $model->status 
                    ];
                    $slug="api/create-client";
                    $method="POST";
                        
                    $globalapi_response = GlobalApiCall::callApi($slug, $method, $request);
                }
            }

                $this->redirect(array('newList'));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    /* public function actionUpdate($id)
      {
      $model=$this->loadModel($id);

      // Uncomment the following line if AJAX validation is needed
      $this->performAjaxValidation($model);

      if(isset($_POST['Clients']))
      {
      $model->attributes=$_POST['Clients'];

      $model->updated_by = yii::app()->user->id;
      $model->updated_date = date('Y-m-d');

      if($model->save())
      $this->redirect(array('view','id'=>$model->cid));
      }

      $this->render('update',array(
      'model'=>$model,
      ));
      }
     */


    public function actionUpdate($id) {
	    $tblpx = Yii::app()->db->tablePrefix;	
		 if(isset($_GET['layout']))
                $this->layout = false;
        $model = $this->loadModel($id);
        

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);
        
        $userids = array();
        if (isset($_POST['Clients'])) {
            $model->attributes = $_POST['Clients'];
            
            if($_POST['Clients']['project_type'] != 2 )
            {
			$model->local_address = '';
            $model->contact_person = '';
			}else{
            $model->local_address = $_POST['Clients']['local_address'];
            $model->contact_person = $_POST['Clients']['contact_person'];
			}
            
            $model->updated_by = yii::app()->user->id;
            $model->updated_date = date('Y-m-d');
            if (!empty($_POST['Clients']['company_id'])) {
                $company = implode(",",$_POST['Clients']['company_id']);
                $model->company_id = $company;
            } else {
                $model->company_id = NULL;
            } 
            if ($model->save()) {
                
                $pms_api_integration=ApiSettings::model()->pmsIntegrationStatus();
                    if ($_POST['execute_api'] == 1) {
                        if($pms_api_integration ==1){
                            $request = [
                                'origin' => 'coms',
                                'client_id' =>$model->cid,
                                'name' => $model->name,
                                'project_type' => $model->project_type,

protected/views/clients/_form.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */
/* @var $form CActiveForm */
$pms_api_integration = ApiSettings::model()->pmsIntegrationStatus();
$crm_api_integration = ApiSettings::model()->crmIntegrationStatus();
?>

<div class="">
    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'clients-form',
        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'validateOnChange' => true,
            'validateOnType' => false,
        ),
    )); ?>
    <div>
        <div class="row">
            <input type="hidden" id="pms_integration" value="<?php echo $pms_api_integration; ?>">
            <div class="col-md-3 col-sm-4 form-group">
                <?php echo $form->labelEx($model, 'name'); ?>
                <?php
                $readonly = ($crm_api_integration == 1) ? ['readonly' => true] : [];
                echo $form->textField(
                    $model,
                    'name',
                    array_merge(['size' => 66, 'maxlength' => 100, 'class' => 'form-control'], $readonly)
                ); ?>
                <?php echo $form->error($model, 'name'); ?>
            </div>
            <div class="col-md-3 col-sm-4 form-group">
                <?php echo $form->labelEx($model, 'project_type'); ?>
                <?php echo $form->dropDownList($model, 'project_type', CHtml::listData(ProjectType::model()->findAll(array('order' => 'project_type ASC')), 'ptid', 'project_type'), array('class' => 'form-control', 'empty' => '--')); ?>
                <?php echo $form->error($model, 'project_type'); ?>
            </div>
            <div class="col-md-3 col-sm-4 form-group">
                <?php echo $form->labelEx($model, 'phone'); ?>
                <?php echo $form->textField($model, 'phone', array('class' => 'form-control')); ?>
                <?php echo $form->error($model, 'phone'); ?>
            </div>
            <div class="col-md-3 col-sm-4 form-group">
                <?php echo $form->labelEx($model, 'email_id'); ?>
                <?php echo $form->textField($model, 'email_id', array('class' => 'form-control')); ?>
                <?php echo $form->error($model, 'email_id'); ?>
            </div>
            <?php if (!$model->isNewRecord) {
                if ($model->project_type == 2) {
                    ?>
                    <div class="col-md-3 col-sm-4 form-group hidbox">
                        <?php echo $form->labelEx($model, 'contact_person'); ?>
                        <?php echo $form->textField($model, 'contact_person', array('class' => 'form-control')); ?>
                        <?php echo $form->error($model, 'contact_person'); ?>
                    </div>

                    <div class="col-md-3 col-sm-4 form-group hidbox">
                        <?php echo $form->labelEx($model, 'local_address'); ?>
                        <?php echo $form->textArea($model, 'local_address', array('class' => 'form-control')); ?>
                        <?php echo $form->error($model, 'local_address'); ?>
                    </div>

                    <?php
                } else {
                    ?>
                    <div class="col-md-3 col-sm-4 form-group hidbox" style="display: none">
                        <?php echo $form->labelEx($model, 'contact_person'); ?>
                        <?php echo $form->textField($model, 'contact_person', array('class' => 'form-control')); ?>
                        <?php echo $form->error($model, 'contact_person'); ?>
                    </div>
                    <div class="col-md-3 col-sm-4 form-group hidbox" style="display: none">
                        <?php echo $form->labelEx($model, 'local_address'); ?>
                        <?php echo $form->textArea($model, 'local_address', array('class' => 'form-control')); ?>
                        <?php echo $form->error($model, 'local_address'); ?>
                    </div>
                    <?php
                }
            } else { ?>
                <div class="col-md-3 col-sm-4 form-group hidbox" style="display: none">
                    <?php echo $form->labelEx($model, 'contact_person'); ?>
                    <?php echo $form->textField($model, 'contact_person', array('class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'contact_person'); ?>
                </div>


                <div class="col-md-3 col-sm-4 form-group hidbox" style="display: none">
                    <?php echo $form->labelEx($model, 'local_address'); ?>
                    <?php echo $form->textArea($model, 'local_address', array('class' => 'form-control')); ?>
                    <?php echo $form->error($model, 'local_address'); ?>
                </div>

            <?php } ?>
            <div class="col-md-3 col-sm-4 form-group">
                <?php echo $form->labelEx($model, 'gst_no'); ?>
                <?php echo $form->textField($model, 'gst_no', array('class' => 'form-control')); ?>
                <?php echo $form->error($model, 'gst_no'); ?>
            </div>
            <div class="col-md-3 col-sm-4 form-group">
                <?php echo $form->labelEx($model, 'status'); ?>
                <div class="radio_btn">
                    <?php
                    echo $form->radioButtonList($model, 'status', CHtml::listData(Status::model()->findAll(
                        array(
                            'select' => array('sid,caption'),
                            'condition' => 'status_type="active_status"',
                            'order' => 'caption',
                            'distinct' => true
                        )
                    ), 'sid', 'caption'), array('separator' => '', 'display' => 'inline-block', 'class' => 'statusall'));
                    ?>
                </div>
                <?php echo $form->error($model, 'status'); ?>
            </div>
            <!-- </div>
        <div class="row"> -->
            <div class="col-md-3 col-sm-6 form-group">
                <?php echo $form->labelEx($model, 'address'); ?>
                <?php echo $form->textArea($model, 'address', array('rows' => 3, 'cols' => 50, 'class' => 'form-control')); ?>
                <?php echo $form->error($model, 'address'); ?>
            </div>
            <div class="col-md-3 col-sm-6 form-group">
                <?php echo $form->labelEx($model, 'description'); ?>
                <?php echo $form->textArea($model, 'description', array('class' => 'form-control', 'rows' => 3, 'cols' => 50)); ?>
                <?php echo $form->error($model, 'description'); ?>
            </div>
            <div class="col-md-3 col-sm-6 form-group">
                <label>Company </label>&nbsp;<span class="required">*</span>
                <ul class="checkboxList">
                    <?php
                    $user = Users::model()->findByPk(Yii::app()->user->id);
                    $arrVal = explode(',', $user->company_id);
                    $newQuery = "";
                    foreach ($arrVal as $arr) {
                        if ($newQuery)
                            $newQuery .= ' OR';
                        $newQuery .= " FIND_IN_SET('" . $arr . "', id)";
                    }
                    $typelist = Company::model()->findAll(array('condition' => $newQuery));
                    $assigned_company_array = array();
                    if (!$model->isNewRecord) {
                        $assigned_types = Clients::model()->find(array('condition' => 'cid=' . $model->cid));
                        $assigned_company_array = explode(",", $assigned_types->company_id);
                        if ((isset(Yii::app()->user->role) && (in_array('/clients/companypermission', Yii::app()->user->menuauthlist)))) {
                            $readonly = "";
                        } else {
                            $readonly = "readonly";
                        }

                    } else {
                        $assigned_company_array = "";
                        $readonly = "";
                    }
                    echo CHtml::checkBoxList('Clients[company_id]', $assigned_company_array, CHtml::listData($typelist, 'id', 'name'), array('checkAll' => 'Check all', 'template' => '<li class="checkboxtype compnyall">{input}{label}</li>', 'separator' => '', 'readonly' => $readonly));
                    ?>
                </ul>
                <?php echo $form->error($model, 'company_id'); ?>
            </div>

        </div>
        <div class="row">
            <div class="form-group col-xs-12 text-right">
                <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn-info', 'id' => 'submit-btn')); ?>
                <?php if (!$model->isNewRecord) {
                    echo CHtml::ResetButton('Close', array('onclick' => 'closeaction(this,event);', 'class' => 'btn btn-other'));
                } else {
                    echo CHtml::ResetButton('Reset', array('style' => 'margin-right:3px;', 'class' => 'btn btn-default'));
                    echo CHtml::ResetButton('Close', array('onclick' => 'closeaction(this,event);', 'class' => 'btn btn-other'));
                }
                echo CHtml::hiddenField('execute_api', 0); ?>
            </div>
        </div>
    </div>
    <?php echo $form->hiddenField($model, 'client_mapping_id'); ?>

    <?php $this->endWidget(); ?>

</div><!-- form -->
<script>
    $(document).on("change", "#Clients_project_type", function () {
        var val = $("#Clients_project_type option:selected").text();
        if (val == 'NRI') {
            $('.hidbox').show();
        } else {
            $('.hidbox').hide();
        }
    });

    function countOfLetters(str) {
        var letter = 0;
        for (i = 0; i < str.length; i++) {
            if ((str[i] >= 'A' && str[i] <= 'Z')
                || (str[i] >= 'a' && str[i] <= 'z'))
                letter++;
        }

        return letter;
    }

    $("#Clients_name").keyup(function () {
        var alphabetCount = countOfLetters(this.value);
        var message = "";
        var disabled = false;

        if (alphabetCount < 1) {
            var message = "Invalid Client Name";
            var disabled = true;
        }

        $(this).siblings(".errorMessage").show().html(message).addClass('d-block');
        $(".btn-info").attr('disabled', disabled);

    });
    $(function () {
        var anca_pms_linked = '<?php echo ANCAPMS_LINKED; ?>';
        if (anca_pms_linked) {
            $('#Clients_name').addClass('nonClickable');
            $('#Clients_project_type').addClass('nonClickable');
            $('#Clients_phone').addClass('nonClickable');
            $('#Clients_address').addClass('nonClickable');
            $('.compnyall').addClass('nonClickable');
            $('.statusall').addClass('nonClickable');
        }
    });
    $(document).ready(function () {
        document.getElementById('clients-form').onsubmit = function () {
            var pms_integration = $("#pms_integration").val();
            var client_mapping_id = $("#Clients_client_mapping_id").val();
            if (pms_integration == '1') {
                if (client_mapping_id == '0') {
                    var confirmApiCall = confirm("Do you want to save the client in Pms?");
                    if (confirmApiCall) {
                        document.getElementById('execute_api').value = 1;
                    }
                }
                else if (client_mapping_id != '0') {
                    document.getElementById('execute_api').value = 1;
                }
            }
        };
    });
</script>

protected/views/clients/_newsearch.php
<?php
/* @var $this ProjectsController */
/* @var $model Projects */
/* @var $form CActiveForm */
?>



<div class="">
	
	<div class="">
		<?php $form=$this->beginWidget('CActiveForm', array(
			'action'=>Yii::app()->createUrl($this->route),
			'method'=>'get',
		)); ?>
		<?php echo $form->label($model,'Filter By'); ?>
		<?php echo $form->textField($model,'name',array('size'=>30,'maxlength'=>100,'placeholder' => 'Name')); ?>

			<?php echo CHtml::submitButton('Go'); ?>
			<?php echo CHtml::resetButton('Clear', array('onclick' => 'javascript:location.href="'. $this->createUrl('newlist').'"')); ?> 
		<?php $this->endWidget(); ?>
	</div>
</div>
				

protected/views/clients/_search.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'cid'); ?>
		<?php echo $form->textField($model,'cid'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_date'); ?>
		<?php echo $form->textField($model,'created_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_by'); ?>
		<?php echo $form->textField($model,'created_by'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_date'); ?>
		<?php echo $form->textField($model,'updated_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_by'); ?>
		<?php echo $form->textField($model,'updated_by'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/clients/admin.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs = array(
    'Clients' => array('index'),
    'Manage',
);

$this->menu = array(
    array('label' => 'List Clients', 'url' => array('index')),
    array('label' => 'Create Clients', 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('clients-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Clients</h1>

<?php echo CHtml::link('Advanced Search', '#', array('class' => 'search-button')); ?>
<div class="search-form" style="display:none">
    <?php
    $this->renderPartial('_search', array(
        'model' => $model,
    ));
    ?>
</div><!-- search-form -->

<?php
$createUrl = $this->createUrl('create', array("asDialog" => 1, "gridId" => 'address-grid'));
echo CHtml::link('Create Client', '#', array('onclick' => "$('#cru-frame').attr('src','$createUrl '); $('#cru-dialog').dialog('open');"));
?>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'clients-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        array('class' => 'IndexColumn', 'header' => 'Sl.No.',),
        array('name'=>'cid', 'htmlOptions' => array('width' => '40px','style'=>'font-weight: bold;text-align:center')),  
        'name',
        array(
            'name' => 'project_type',
            'value' => '$data->projectType->project_type',
            'type' => 'raw',
            'filter' => CHtml::listData(ProjectType::model()->findAll(
                            array(
                                'select' => array('ptid,project_type'),
                                'order' => 'project_type',
                                'distinct' => true
                    )), "ptid", "project_type")
        ),
        'description',
        array(
            'name' => 'status',
            'value' => '$data->status0->caption',
            'type' => 'raw',
            'filter' => CHtml::listData(Status::model()->findAll(
                            array(
                                'select' => array('sid,caption'),
                                'condition' => 'status_type="active_status"',
                                'order' => 'status_type',
                                'distinct' => true
                    )), "sid", "caption")
        ),
        'created_date',
        array(
            'class' => 'CButtonColumn',
            'buttons' => array('view' =>
                array(
                    'url' => 'Yii::app()->createUrl("clients/view", array("id"=>$data->cid,"asDialog"=>1))',
                    'options' => array(
                        'ajax' => array(
                            'type' => 'POST',
                            // ajax post will use 'url' specified above 
                            'url' => "js:$(this).attr('href')",
                            'update' => '#id_view',
                        ),
                    ),
                ),
                'update' =>
                array(
                    'url' => '$this->grid->controller->createUrl("update", array("id"=>$data->primaryKey,"asDialog"=>1,"gridId"=>$this->grid->id))',
                    'click' => 'function(){$("#cru-frame").attr("src",$(this).attr("href")); $("#cru-dialog").dialog("open");  return false;}',
                ),
            ),
        ),
    ),
));
?>
<?php
//--------------------- begin new code --------------------------
// add the (closed) dialog for the iframe
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id' => 'cru-dialog',
    'options' => array(
        'title' => 'Detail view',
        'autoOpen' => false,
        'modal' => false,
        'width' => 620,
        'height' => 560,
    ),
));
?>
<iframe id="cru-frame" width="600" height="500" scrolling="auto"></iframe>
<?php
$this->endWidget();
//--------------------- end new code --------------------------
//the dialog
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id' => 'dlg-clients-view',
    'options' => array(
        'title' => 'Detail view',
        'autoOpen' => false, //important!
        'modal' => true,
        'width' => 550,
        'height' => 470,
    ),
));
?>
<div id="id_view"></div>
<?php $this->endWidget(); ?>

protected/views/clients/create.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs = array(
    'Clients' => array('index'),
    'Create',
);

/*$this->menu=array(
    array('label'=>'List Clients', 'url'=>array('index')),
    array('label'=>'Manage Clients', 'url'=>array('admin')),
);*/
?>
<div class="entries-wrapper">
    <div class="row">
        <div class="col-xs-12">
            <div class="heading-title">Add Client</div>
            <div class="dotted-line"></div>
        </div>
    </div>
    <?php echo $this->renderPartial('_form', array('model' => $model)); ?>
</div>

protected/views/clients/index.php
)
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs = array(
    'Clients' => array('index'),
    'Index',
);

$this->menu = array(
    array('label' => 'List Clients', 'url' => array('index')),
    array('label' => 'Create Clients', 'url' => array('create')),
    array('label' => 'Manage Clients', 'url' => array('admin')),
    array('label' => 'Manage Project types', 'url' => array('/projectType/admin')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('clients-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div style="float:left;"><h2>List Clients</h2></div>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'clients-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        array('class' => 'IndexColumn', 'header' => 'Sl.No.',),
        array('name'=>'cid', 'htmlOptions' => array('width' => '40px','style'=>'font-weight: bold;text-align:center')),       
          array(
        'name'  => 'name',
        'value' => 'CHtml::link($data->name, Yii::app()
 ->createUrl("clients/view",array("id"=>$data->cid)))',
        'type'  => 'raw',
    ),
        array(
            'name' => 'project_type',
            'value' => '$data->projectType->project_type',
            'type' => 'raw',
            'filter' => CHtml::listData(ProjectType::model()->findAll(
                            array(
                                'select' => array('ptid,project_type'),
                                'order' => 'project_type',
                                'distinct' => true
                    )), "ptid", "project_type")
        ),
        'description',
        array(
            'name' => 'status',
            'value' => '$data->status0->caption',
            'type' => 'raw',
            'filter' => CHtml::listData(Status::model()->findAll(
                            array(
                                'select' => array('sid,caption'),
                                'condition' => 'status_type="active_status"',
                                'order' => 'status_type',
                                'distinct' => true
                    )), "sid", "caption")
        ),
        'created_date',
              array(
        'class'=>'CButtonColumn',
         'header'=>'Toggle Details',
          'template'=>'{view}',
  
          ),
    ),
));
?>